apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc
  labels:
    app: myjavaapp
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: myjavaapp
  

  # -p 30001:80